### ISSUE TITLE
Install update

### ISSUE THREAD

**Issue by rockrabbit** [eLVee1991/youtubeblock#5]
After clone (raspberry pi on Jessie)

```
sudo apt-get install python-pip

sudo pip install pexpect
```

**Comment by eLVee1991** [comment]
I didn't need to run that command when first using the script. You did?

**Comment by rockrabbit** [comment]
Yes, there was no Python on my fresh Pi... thus I had to look up and first installed Python 3.. that did not work and then learnt about Python 2.. which that is the line I gave.

So I'm helping you with your wonderful script for newbies to install Python! :)

**Comment by eLVee1991** [comment]
Thanks! I'll add that to the readme.md. Usually it comes pre-installed, but since that isn't the case for you, it could be the case for others.

**Comment by rockrabbit** [comment]
Remember, Stretch Light is not the same as the other builds.. its light! ;)

https://www.raspberrypi.org/downloads/raspbian/
